### ISSUE TITLE
Add option to run SAST(tfsec) against mach-composer generated code

### ISSUE THREAD

**Issue by MichielBijland** [labd/mach-composer#137]
It would be useful to run a SAST engine against the output from the mach-composer for the developer to check their code but also when deploying mach-composer using ci/cd pipeline to stop insecure code from deploying.

[tfsec](https://github.com/aquasecurity/tfsec) seems to be a good option to start with.

example command and output:
```
mach scan

 Result 1

  [aws-api-gateway-enable-access-logging][MEDIUM] Resource 'aws_apigatewayv2_stage.internal_default' is missing access log settings block.
  .../site.tf:123-137


     120 |   route_key = "$default"
     121 | }
     122 | 
     123 | resource "aws_apigatewayv2_stage" "internal_default" {
     124 |   name        = "$default"
     125 |   description = "Stage for default release"
     126 |   api_id      = aws_apigatewayv2_api.internal_gateway.id
     127 |   auto_deploy = true
     128 | 
     129 | 
     130 |   depends_on = [
     131 |     module.algolia,
     132 |     module.amplience,
     133 |     module.page-resolver,
     134 |     module.payment-orchestration,
     135 |     module.payment-stripe,
     136 |   ]
     137 | }
     138 | 
     139 | resource "aws_acm_certificate" "internal" {
     140 |   domain_name       = "..."

  Legacy ID:  AWS061
  Impact:     Logging provides vital information about access and usage
  Resolution: Enable logging for API Gateway stages

```
we could then support multiple sast engines tfsec, snyk.io, terrascan, etc using command
```
mach scan list
  tfsec (current default)
  snyk
```

```
mach scan --engine=snyk
Testing site.tf...


Infrastructure as code issues:
  ✗ API Gateway access logging disabled [Low Severity] [SNYK-CC-TF-138] in API Gateway (REST APIs)
    introduced by resource > aws_apigatewayv2_stage[internal_default] > access_log_settings
```

One drawback is bundling of the scan engines with mach-composer and it's size, we could reduce the impact by making docker tags with and without sast scanning engines or split them even

```
mach
mach-tfsec
mach-snyk
```

**Comment by pimvernooij** [comment]
Rererencing #75

**Comment by pimvernooij** [comment]
Hey @MichielBijland,
How would this work from a workflow perspective? a seperate command `scan` would allow for skipping it, so we could also choose for a more configuration based implementation that always runs as part of a pipeline (and implement a `--skip-sast` flag?)?

```
mach_composer:
  version: 1.1
global:
    terraform_config:
        ...
        sast:
            tfsec: ...
            snyk: ...
            cfguard: ...
            atlantis: ...
```

**Comment by pimvernooij** [comment]
On the other hand, having a `mach scan` command would allow a sequence of `mach plan`, `mach scan` and `mach apply` I suppose?

**Comment by tleguijt** [comment]
Sounds like a good addition!
I'm also in favour of initially having this as a separate command. In a later stage we can see if we want to somehow integrate it more in the configuration and enforce it in order to perform a `mach apply`.

Having a separate `mach plan` and `mach apply` also asks for the ability to feed a terraform plan to `mach apply` (which might get tricky when rolling out several sites in one go), and same applies when performing a SAST on the terraform plan. I will create a separate ticket for this.

Another good point you brought up is the docker image size.
We currently already have this issue already with having the azure cli included in the image which is a big package and not needed for if you're managing a stack on AWS.
Same goes for the security scans.
So next to the `mach`, `mach-tfsec` (or `mach:tfsec`) etc you'll probably also want the `azure` option in there (and where does it stop?).

**Comment by pimvernooij** [comment]
What are we talking about in size? Perhaps do a small test to see how big the images will become?

**Comment by MichielBijland** [comment]
Closing ticket because we now have a init command, which gives enough information with a terraform plan for SAST scanners.
